config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: [:edit, :update]
    resources :featured_collections, except: [:edit, :update]
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    root to: 'dashboard#index'
  end

  resources :users, except: [:index, :create, :destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      post :bid
      post :report
      post :create_contract
    end
  end
  resources :collections, only: [:new, :show, :create]  do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_fixed_price
      post :owner_transfer
      post :burn
    end
  end

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: [:create, :update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  skip_before_action :authenticate_user, only: [:show]
  skip_before_action :is_approved, only: [:show]
  # before_action :set_collection, only: [:show, :bid, :execute_max_bid, :remove_from_sale, :execute_bid, :buy]
  before_action :set_collection, except: [:new, :create, :update_token_id, :sign_metadata_hash]

  skip_before_action :verify_authenticity_token


  def new
    @collection_type = params[:type]
  end

  def show
    @tab = params[:tab]
    @activities = PaperTrail::Version.where(item_type: "Collection", item_id: @collection.id).order("created_at desc")
    @max_bid = @collection.max_bid
    set_collection_gon
  end

  def create
    begin
      # ActiveRecord::Base.transaction do
        @collection = Collection.new(collection_params)
        @collection.state = :pending
        # ITS A RAND STRING FOR IDENTIFIYING THE COLLECTION. NOT CONTRACT ADDRESS
        @collection.address = Collection.generate_uniq_token
        @collection.creator_id = current_user.id
        @collection.royalty = 0 unless @collection.royalty.present?
        @collection.owner_id = current_user.id
        @collection.data = JSON.parse(collection_params[:data]) if collection_params[:data].present?
        @collection.owned_tokens = @collection.no_of_copies
        if @collection.valid?
          @collection.save
          @metadata_hash = Api::Pinata.new.upload(@collection)
          # PaperTrail.request(enabled: false) { @collection.approve! }
        else
          @errors = @collection.errors.full_messages
        end
      # end
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def bid
    begin
      @collection.place_bid(bid_params)
    rescue Exception => e
      Rails.logger.warn "################## Exception while creating BID ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def remove_from_sale
    if @collection.is_owner?(current_user)
      @collection.remove_from_sale
      @collection.cancel_bids
    end
    redirect_to collection_path(@collection.address)
  end

  def sell
    begin
      ActiveRecord::Base.transaction do
        @redirect_address = @collection.execute_bid(params[:address], params[:bid_id], params[:transaction_hash]) if @collection.is_owner?(current_user)
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while selling collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def buy
    begin
      ActiveRecord::Base.transaction do
        @redirect_address = @collection.direct_buy(current_user, params[:quantity].to_i, params[:transaction_hash])
      end
    rescue Exception => e
      Rails.logger.warn "################## Exception while buying collection ##################"
      Rails.logger.warn "ERROR: #{e.message}, PARAMS: #{params.inspect}"
      Rails.logger.warn $!.backtrace[0..20].join("\n")
      @errors = e.message
    end
  end

  def update_token_id
    collection = current_user.collections.unscoped.where(address: params[:collectionId]).take
    collection.approve! unless collection.instant_sale_price.present?
    collection.update(token: params[:tokenId])
  end

  def change_price
    @collection.assign_attributes(change_price_params)
    @collection.save
  end

  def burn
    @collection.burn! if @collection.may_burn?
  end

  def transfer_token
    new_owner = User.find_by_address(params[:user_id])
    if new_owner.present?
      @collection.hand_over_to_owner(new_owner.id)
    else
      @errors = [t("collections.show.invalid_user")]
    end
  end

  def sign_metadata_hash
    sign = if params[:contract_address].present?
      collection = current_user.collections.unscoped.where(address: params[:id]).first
      obj = Utils::Web3.new
      obj.sign_metadata_hash(params[:contract_address], collection.metadata_hash)
    else
      ""
    end
    render json: sign
  end

  def fetch_details
    render json: {data: @collection.fetch_details(params[:bid_id], params[:erc20_address])}
  end

  def fetch_transfer_user
    user = User.validate_user(params[:address])
    if user && user.is_approved? && user.is_active?
      render json: {address: user.address}
    else
      render json: {error: 'User not found or not activated yet. Please provide address of the user registered in the application'}
    end

  end

  def sign_fixed_price
    collection = current_user.collections.unscoped.where(address: params[:id]).take
    collection.approve! if collection.pending?
    collection.update(sign_instant_sale_price: params[:sign])
  end

  def owner_transfer
    collection = current_user.collections.unscoped.where(address: params[:id]).take
    recipient_user = User.where(address: params[:recipient_address]).first
    collection.hand_over_to_owner(recipient_user.id, params[:transaction_hash], collection.owned_tokens)
  end

  private

  # Collection param from React  
  # def collection_params
  #   params.permit(:name, :description, :collection_address, :put_on_sale, :instant_sale_price, :unlock_on_purchase,
  #     :collection_category, :no_of_copies, :attachment)
  # end

  def collection_params
    params['collection']['category'] = params['collection']['category'].present? ? params['collection']['category'].split(",") : []
    params['collection']['nft_contract_id'] = NftContract.get_shared_id(params[:collection][:collection_type]) if params['chooseCollection'] == 'nft'
    params['collection']['erc20_token_id'] = Erc20Token.where(address: params[:collection][:currency]).first&.id if params[:collection][:currency].present?
    params.require(:collection).permit(:name, :description, :collection_address, :put_on_sale, :instant_sale_enabled, :instant_sale_price, :unlock_on_purchase,
                               :bid_id, :no_of_copies, :attachment, :cover, :data, :collection_type, :royalty, :nft_contract_id, :unlock_description,
                               :erc20_token_id, category: [])
  end

  def change_price_params
    params[:collection][:put_on_sale] = false if params[:collection][:put_on_sale].nil?
    params[:collection][:unlock_on_purchase] = false if params[:collection][:unlock_on_purchase].nil?
    unless params[:collection][:instant_sale_enabled]
      params[:collection][:instant_sale_enabled] = false
      params[:collection][:instant_sale_price] = nil
    end
    params.require(:collection).permit(:put_on_sale, :instant_sale_enabled, :instant_sale_price, :unlock_on_purchase, :unlock_description, :erc20_token_id)
  end

  def bid_params
    params[:user_id] = current_user.id
    params.permit(:sign, :quantity, :user_id, details: {})
  end

  def set_collection
    @collection = Collection.unscoped.find_by(address: params[:id])
    redirect_to root_path unless @collection.present?
  end

  def set_gon
    gon.collection_data = @collection.gon_data
  end

  def set_collection_gon
    gon.collection_data = @collection.gon_data
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def cover_url(collection)
    return '/assets/dummy-image.jpg' if unauthorized_to_show_attachment(collection)
    attachment = ['image/png', 'image/jpeg', 'image/gif', 'image/webp'].include?(collection.attachment.content_type) ? collection.attachment_with_variant(:thumb) : collection.cover
    attachment.present? ? url_for(attachment) : '/assets/banner-1.png'
    # pinata_url(collection)
  end

  def attachment_tag(collection)
    attachment = collection.attachment
    return image_tag '/assets/dummy-image.jpg', class: "img-responsive" if unauthorized_to_show_attachment(collection)

    if ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
      audio_tag url_for(attachment), size: "550x400", controls: true
    elsif ['video/mp4', 'video/webm'].include?(attachment.content_type)
      video_tag url_for(attachment), class: "video-responsive", controls: true
    else
      # image_tag pinata_url(collection), class: "img-responsive"
      image_tag url_for(attachment), class: "img-responsive"
    end
  end

  def cover_tag(collection)
    attachment = collection.attachment
    if ['audio/mp3', 'audio/webm', 'audio/mpeg'].include?(attachment.content_type)
      image_tag cover_url(collection), class: "img-responsive"
    end
  end

  def unauthorized_to_show_attachment(collection)
    # collection.unlock_on_purchase? && (!current_user.present? || (current_user && current_user != collection.owner))
    return false
  end

  def pinata_url(collection)
    collection.image_hash.present? ? "https://gateway.pinata.cloud/ipfs/#{collection.image_hash}" : '/assets/dummy-image.jpg'
  end
end

app/views/collections/_accept_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart acceptBidStart fa fa-check-circle grey"></i>
    <i class="allProgress acceptBidProgress fa fa-spinner fa-pulse hide"></i>
    <i class="allDone acceptBidDone fa fa-check-circle hide"></i>
    <i class="allRetry acceptBidRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4><%= t('shared.accept_bid')%></h4>
    <p class="para-color"><%= t('shared.transaction_with_wallet')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart acceptBidStart disabledLink grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress acceptBidProgress disabledLink hide"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone acceptBidDone disabledLink hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry acceptBidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_approve_execute_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart approveExecbidStart fa fa-check-circle hide grey"></i>
    <i class="allProgress approveExecbidProgress fa fa-spinner fa-pulse"></i>
    <i class="allDone approveExecbidDone fa fa-check-circle hide"></i>
    <i class="allRetry approveExecbidRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4><%= t('collections.show.approve')%></h4>
    <p class="para-color"><%= t('collections.show.approve_terms')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart approveExecbidStart disabledLink hide grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress approveExecbidProgress disabledLink"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone approveExecbidDone disabledLink hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry approveExecbidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_buy_modal.html.erb
<div class="zoom-anim-dialog mfp-hide modal sm_modal" id="Buy-modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <%= form_tag "javascript:void(0)", method: :post, remote: true, id: 'buyForm' do %>
    <h4 class="modal-title share_link_page_h4"><%= t('collections.show.checkout') %></h4>
    <div class="modal-body pt-10 pb-10">
      <% erc20_token = @collection.erc20_token %>
      <span id="buyContractAddress" class="hide"><%= erc20_token.address %></span>
      <span id="buyContractDecimals" class="hide"><%= erc20_token.decimals %></span>
      <p class="buynow-content">
        <span class="innertitle"><%= t('collections.show.you_are_abt_purchase') %></span>
        <span class="frm-title"><b><%= @collection.name %></b>,</span>
        <span class="frm-desc"><%= @collection.description %>
          <span class="frm-from" data-toggle="tooltip" data-placement="top" title="<%= @collection.owner.address %>">from <%= link_to @collection.owner.full_name, user_path(@collection.owner.address), target: '_blank' %></span></span>
      </p>
      <div class="placebidbuy_valbox">
        <% price, symbol = @collection.sale_price %>
        <div class="form-group bidBuyInputs">
          <div>
            <label for="recipient-name" class="col-form-label"><%= t('collections.show.quantity_available', token: @collection.owned_tokens.to_i) %></label>
            <input type="number" id='buy_qty' name="buy[quantity]" maxQuantity="<%= @collection.owned_tokens.to_i %>" class="sign__input" placeholder="Enter quantity" required/>
          </div>
          <div>
            <label for="recipient-name" class="col-form-label"><%= t('collections.show.buy_price') %></label>
            <span class="price_currency sign__input">
                  <span id="buy_price" price="<%= price %>"><%= price %></span><span id="buy_currency"><%= symbol %></span>
                </span>
          </div>
        </div>
        <div class="flex_box_inputs">
          <span class="price-amt-content"><%= t('collections.show.your_balance') %></span>
          <span class="price-amt-val" id="current_balance"><%= current_balance %> <%= Rails.application.credentials.config[:base_coin] %></span>
        </div>
        <div class="flex_box_inputs">
          <span class="price-amt-content"><%= t('collections.show.your_buy_balance') %></span>
          <span class="price-amt-val"><span class="ercCurBalance">0</span> <%= symbol %></span>
        </div>
        <div class="flex_box_inputs">
          <span class="price-amt-content"><%= t('collections.show.service_fee') %></span>
          <span class="price-amt-val"><span id="buy-amt-dp">0</span> <%= symbol %></span>
        </div>
        <div class="flex_box_inputs">
          <span class="price-amt-content"><%= t('collections.show.you_will_pay') %></span>
          <span class="price-amt-val"><span id="buy-total-amt-dp">0</span> <%= symbol %></span>
        </div>
      </div>
    </div>
    <div class="modal-footer" style="text-align:center">
      <a class="btn bidding-element-btn triggerBuyValidation theme-btn  sign__btn" href="" role="button"><%= t('collections.show.pay') %></a>
    </div>
  <% end %>
</div>

<div class="zoom-anim-dialog mfp-hide modal sm_modal" id="placeBuy">

  <h4 class="modal-title"><%= t('shared.follow_steps') %></h4>

  <div class="modal-body">
    <div class="convertEth">
      <%= render partial: 'convert_eth' %>
    </div>

    <div class="approveBuy">
      <%= render partial: 'approve_buy' %>
    </div>

    <div class="purchaseBuy">
      <%= render partial: 'purchase_buy' %>
    </div>

  </div>
</div>

app/views/collections/_collection_type.html.erb
<section class="create-collectible-section pt-20 pb-20">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="create-collectible-box">
          <div class="create-collectible-box-header">
            <div class="heading-create-collectible main__title">
              <h2 class="mt-0 mb-0"><%= t('collections.form.create_collectible')%></h2>
              <a href="javascript:history.back()"><%= t('shared.go_back')%></a>
            </div>
          </div>
          <div class="create-collectible-box-body">
            <p class="pt-20"><%= t('collections.form.collection_type_text')%></p>
            <p class="pt-20"><%= t('collections.form.collection_type_txt')%></p>

            <div class="create-collectible-button-box">
              <a class="single-multiple-create" href="<%= new_collection_path(type: "single")%>">
                <%= image_tag "single.png" %>
                <p><%= t('collections.form.single')%></p>
              </a>
              <a class="single-multiple-create" href="<%= new_collection_path(type: "multiple") %>">
                <%= image_tag "multiple.png" %>
                <p><%= t('collections.form.multiple')%></p>
              </a>
            </div>
            <p><%= t('collections.form.collection_privacy')%></p>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/collections/_deploy_contract.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="deployProgress fa fa-spinner fa-pulse"></i>
    <i class="deployDone fa fa-check-circle hide"></i>
    <i class="deployRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h3><%= t('collections.form.deploy_contract')%></h3>
    <p class="para-color"><%= t('collections.form.deploy_contract_msg')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="deployProgress disabledLink"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="deployDone hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="deployRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_owner.html.erb
<a href="<%= collection_path(collection.address)%>">
  <div class="token-collections">
    <div class="token-collections-images">
      <%= image_tag url_for(collection.owner.profile_image(:icon)), class: 'img-responsive' %>
      <i class="fa fa-check-circle"></i>
    </div>
    <div class="token-collections-details">
      <p class="para-color"><%= t('collections.show.owner_token', token: (collection.owned_tokens || 1 ))%></p>
      <h4 data-toggle="tooltip" data-placement="top" title="<%= collection.owner.address %>"><%= collection.owner.masked_address(18, 4) %></h4>
    </div>
  </div>
</a>

app/views/collections/_price_change.html.erb
<div id="change-price" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title share_link_page_h4"><%= t('collections.show.change_price') %></h4>
  <%= form_tag(change_price_collection_path, method: :post, remote: true, class: 'change-price-form') do %>
    <%= hidden_field_tag 'id', @collection.address, class: 'nft-detail-name' %>


    <div class="modal-body pl-30 pr-30">
      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.put_on_sale') %></label>
          <p class="para-color"><%= t('shared.pos_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <% if @collection.put_on_sale? %>
              <input type="checkbox" name="collection[put_on_sale]" id="collection-put-on-sale" checked>
            <% else %>
              <input type="checkbox" name="collection[put_on_sale]" id="collection-put-on-sale">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.instant_sale_price') %></label>
          <p class="para-color"><%= t('shared.instant_sale_price_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <input type="checkbox" id="collection_instant_sale_enabled" prevVal="<%= @collection.instant_sale_enabled %>" name="collection[instant_sale_enabled]" <%= 'checked' if @collection.instant_sale_enabled %>>
            <span class="slider round"></span>
          </label>
        </div>
      </div>

      <div id='instPrice' class="row mb-15 <%= 'hide' unless @collection.instant_sale_price.present? %>">
        <div class="col-sm-12">
          <div class="form-group bidBuyInputs bordered">
            <div>
              <input type="text" name="collection[instant_sale_price]" prevVal="<%= @collection.instant_sale_price %>" value="<%= @collection.instant_sale_price %>" class="form-control input-custom sign__input" id="instant-price" placeholder="Enter price for one piece"/>
            </div>
            <div>
              <%= select_tag "collection[erc20_token_id]", options_for_select(Erc20Token.select_options, @collection.erc20_token_id), class: "form-control input-custom sign__input", required: true, prevVal: @collection.erc20_token_id %>
            </div>
          </div>
        </div>
      </div>

      <div class="row mb-15">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('shared.unlock_one_purchased') %></label>
          <p class="para-color"><%= t('shared.unlock_one_purchased_msg') %></p>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
          <label class="switch">
            <% if @collection.unlock_on_purchase? %>
              <input type="checkbox" name="collection[unlock_on_purchase]" id="collection-unlock-on-purchase" checked>
            <% else %>
              <input type="checkbox" name="collection[unlock_on_purchase]" id="collection-unlock-on-purchase">
            <% end %>
            <span class="slider round"></span>
          </label>
        </div>
      </div>
      <div class="row mb-15 unlock-description-section <%= 'hide' unless @collection.unlock_on_purchase? %>">
        <div class="col-md-8 col-sm-8 col-xs-8">
          <label><%= t('collections.show.unlock_description') %></label>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" name="collection[unlock_description]" class="form-control input-custom sign__input" id="collection-unlock-description" placeholder="Enter unlock description" value="<%= @collection.unlock_description %>"/>
          </div>
        </div>
      </div>

    </div>
    <div class="modal-footer">
      <%= submit_tag 'Update', class: 'hide', id: 'submitPriceChange', 'data-disable-with': "<i class='fa fa-spinner fa-spin'></i> Updating...".html_safe %>
      <a class="btn bidding-element-btn triggerPriceChange theme-btn" href="javascript:void(0)" role="button">Update</a>
      <a class="bidding-element-btn secondary-btn" data-dismiss="modal" role="button">Cancel</a>
    </div>
  <% end %>
</div>


<div class="zoom-anim-dialog mfp-hide modal sm_modal" id="priceChange">
  <h4 class="modal-title share_link_page_h4"><%= t('shared.follow_steps') %></h4>
  <div class="modal-body">

    <div class="approveFlow">
      <%= render partial: 'approve' %>
    </div>

    <div class="signFixedPrice hide">
      <%= render partial: 'sign_fixed_price' %>
    </div>
  </div>
</div>

app/views/collections/_put_on_sale.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart putOnSaleStart fa fa-check-circle grey"></i>
    <i class="allProgress putOnSaleProgress fa fa-spinner fa-pulse hide"></i>
    <i class="allDone putOnSaleDone fa fa-check-circle hide"></i>
    <i class="allRetry putOnSaleRetry fa fa-check-circle hide grey"></i>
  </div>
  <div class="follow-step-content">
    <h4>Put on sale</h4>
    <p class="para-color">Sign message to put on sale</p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart putOnSaleStart disabledLink grey">Start</a>
    <a href="javascript:void(0)" class="allProgress putOnSaleProgress disabledLink hide">In Progress..</a>
    <a href="javascript:void(0)" class="allDone putOnSaleDone hide">Done</a>
    <a href="javascript:void(0)" class="allRetry putOnSaleRetry hide">Try again</a>
  </div>
</div>

app/views/collections/_sign_bid.html.erb
<div class="follow-step-block">
  <div class="follow-step-icon">
    <i class="allStart signbidStart fa fa-check-circle grey"></i>
    <i class="allProgress signbidProgress fa fa-spinner fa-pulse hide"></i>
    <i class="allDone signbidDone fa fa-check-circle hide"></i>
    <i class="allRetry signbidRetry fa fa-check-circle grey"></i>
  </div>
  <div class="follow-step-content">
    <h4><%= t('collections.show.signature')%></h4> 
    <p class="para-color"><%= t('collections.show.create_a_signature')%></p>
  </div>
  <div class="follow-step-button">
    <a href="javascript:void(0)" class="allStart signbidStart disabledLink grey"><%= t('shared.start')%></a>
    <a href="javascript:void(0)" class="allProgress signbidProgress disabledLink hide"><%= t('shared.in_progress')%></a>
    <a href="javascript:void(0)" class="allDone signbidDone hide"><%= t('shared.done')%></a>
    <a href="javascript:void(0)" class="allRetry signbidRetry hide"><%= t('shared.try_again')%></a>
  </div>
</div>

app/views/collections/_success.html.erb
<div className="follow-step-block">
    <div class="follow-step-icon">
      <i class="fa fa-check-circle"></i>
    </div>
    <div class="follow-step-content">
      <h4><%= t('collections.collection')%></h4>
      <p class="para-color"><%= t('collections.successfully_minted')%></p>
    </div>
    <div class="follow-step-button themeBG">
      <a href="<%= my_items_path %>"><%= t('shared.go_to_my_items')%></a>
    </div>
</div>

app/views/collections/_user_profile_image.html.erb
<div class="token-collections-images">
  <%= image_tag url_for(user.profile_image(:icon)), class: 'img-responsive' %>
  <i class="fa fa-check-circle"></i>
</div>

app/views/collections/change_price.js.erb
toastr.success("<%= t('collections.show.change_price_message') %>")
$("#change-price").modal("hide");
$("#priceChange").modal("hide");
window.location.reload();

app/views/collections/create.js.erb
<% if @errors.present? %>
  $("#collectionCreateForm :input").prop("disabled", false);
  <%= custom_error_flash(@errors, 'error') %>
<% else %>
  <% contract_type = @collection.contract_type || (@collection.multiple? ? 'nft1155' : 'nft721') %>
  <% if @collection.nft_contract_id.present? %>
    $('#collection_contract_address').val("<%= @collection.nft_contract.address %>")
  <% end %>
  $('#collection_contract_type').val("<%= contract_type %>")
  $('#collection_id').val("<%= @collection.address %>")
  $('#collection_token_uri').val("<%= @metadata_hash %>")
  $('#collection_supply').val("<%= @collection.no_of_copies %>")
  $('#collection_royalty_fee').val("<%= @collection.royalty_fee %>")
  <% if @collection.shared? %>
    initCollectionCreate("<%= @collection.nft_contract.address %>", '<%= contract_type %>')
  <% else %>
    startContractDeploy("<%= contract_type %>")
  <% end %>
<% end %>