config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: [:edit, :update]
    resources :featured_collections, except: [:edit, :update]
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    root to: 'dashboard#index'
  end

  resources :users, except: [:index, :create, :destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      post :bid
      post :report
      post :create_contract
    end
  end
  resources :collections, only: [:new, :show, :create]  do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_fixed_price
      post :owner_transfer
      post :burn
    end
  end

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: [:create, :update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @user_count = User.all.count
    @collection_count = Collection.all.count
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate_user
  skip_before_action :is_approved

  def index
    set_categories_by_filter
    @likes = current_user ? current_user.likes.pluck(:collection_id) : []
    @hot_bids = Collection.top_bids(30).with_attached_attachment
    @featured_users = FeaturedUser.limit(5).map(&:user)
    @featured_collections = FeaturedCollection.limit(5).map(&:collection).compact
    # @hot_collections = Collection.group(:owner).count
    top_buyers_and_sellers
  end

  def set_categories_by_filter
    params[:page_no] ||= 1
    @category_collections = params[:query].present? ? Collection.search("*#{params[:query].strip}*").records : Collection
    @category_collections = @category_collections.get_with_sort_option(params[:sort_by])
    @category_collections = @category_collections.where("category like ?", "%#{params[:category]}%") if params[:category].present?
    @category_collections = @category_collections.with_attached_attachment.paginate(page: params[:page_no] || 1)
  end

  def top_buyers_and_sellers
    @top_sellers = User.top_seller(params[:days]).with_attached_attachment
    @top_buyers = User.top_buyer(params[:days]).with_attached_attachment
  end

  def search
    if params[:tab] =='users'
      @users = User.search("*#{params[:query]}*").records
    else
      params[:page_no] ||= 1
      @collections = params[:query].present? ? Collection.search("*#{params[:query].strip}*").records : Collection
      @collections= @collections.with_attached_attachment.paginate(page: params[:page_no] || 1)
    end
  end

  def notifications
    Notification.unread(current_user).update_all(is_read: true) if Notification.unread(current_user).present?
    @notifications = current_user.notifications
  end

  def contract_abi
    shared = ActiveModel::Type::Boolean.new.cast(params[:shared])
    abi = if params[:contract_address].present? && (params[:type] == 'erc20' || shared)
            { abi: Api::Etherscan.new.contract_abi(params[:contract_address]), bytecode: '' }
          elsif(!shared)
            if params[:type] == 'nft721'
              Utils::Abi.nft721
            elsif params[:type] == 'nft1155'
              Utils::Abi.nft1155
            end
          else
            {}
          end
    render json: {compiled_contract_details: abi}
  end
end

app/views/dashboard/_collection_card.html.erb
<!-- 
<div class="my-explore-div all games">
<div class="my-explore-div all photography">
<div class="my-explore-div all art">
-->

<% collection_attachment = collection.get_attachment(current_user)%>
<div class="card">
  <div class="t_c">

    <a href="<%= collection_path(collection.address)%>" class="card__cover">
        <span class="collection-card-img" style="background-image: url('<%= cover_url(collection) %>')">
           <%= image_tag cover_url(collection)%>
        </span>
    </a>
    <% if current_user %>
        <%= react_component("collections/like", address: current_user.address, likes: collection.likes, collectionId: collection.id,likes_count: collection.likes.count) %>
    <% else %>
        <button class="card__likes heart">
          <i class="far fa-heart"></i>
          <i class="fas fa-heart"></i>
          <span><%= collection.likes.count%></span>
        </button>
        
    <% end %>

  </div>
  <div class="grid-box">
    <h3 class="card__title" data-toggle="tooltip" data-placement="top" title="<%= collection.title %>">
      <a href="<%= collection_path(collection.address)%>"><%= collection.title %></a>
    </h3>

    <div class="card__author">
      <%= image_tag collection.owner.profile_image %>
      <% if collection.owner.is_verified %>
          <i class="fa fa-check-circle" aria-hidden="true"></i>
      <% end %>
      <a href="<%=user_path(collection.owner.address)%>" data-toggle="tooltip" data-placement="top" title="@<%= collection.owner.full_name%>">@<%= collection.owner.full_name%></a>
    </div>
  </div>
  <div class="card__info">
    <div class="card__price">
      <span><%= t('shared.reserve_price')%></span>
      <% if collection.instant_sale_price%>
       <span><%=collection.instant_sale_price%> ETH</span>  
      <% else %>
        <% if collection.max_bid %>
          <p class="bid_status">Highest bid <b><%= collection.max_bid.value %></b></p>
        <%else%>
          <span>No active Bids</span> 
        <% end %>
      <%end%>
    </div>
  </div>
</div>

app/views/dashboard/_collection_card_by_categories.html.erb
<% if @category_collections.present? %>
  <% category_collections.each do |collection| %>
    <div class="col-12 col-md-6 col-lg-3">
      <%= render "/dashboard/collection_card", collection: collection %>
    </div>
  <% end %>
<% elsif params[:page] == 1 %>
  <% 5.times do %>
    <%= render partial: 'common/empty_card_collection' %>
  <% end %>
<% end %>

app/views/dashboard/_featured_user.html.erb
<div class="col-md-3 col-sm-6 col-xs-12 custom-width-res-1">
  <a href="#">
    <div class="featured-creators-box">
      <div class="featured-creators-box-img">
        <div class="featured-creators-box-img-bg" style="background-image: url(<%= url_for(user.banner_image) %>);">
          <%= image_tag url_for(user.banner_image), class: 'img-responsive' %>
        </div>
        <div class="featured-creators-box-img-profile">
          <%= image_tag url_for(user.profile_image), class: 'img-responsive' %>
        </div>
      </div>
      <div class="featured-creators-box-content">
        <h4><%= user.name %></h4>
        <!--<a href="#">@jonmonaghan</a>-->
      </div>
    </div>
  </a>
</div>

app/views/dashboard/_hot_bids.html.erb
<div class="item">
  <div class="box-hot-bids">
    <%= render partial: 'common/collection_card', locals: {collection: collection} %>
  </div>
</div>

app/views/dashboard/_hot_collection.html.erb
<div class="col-md-3 col-sm-6 col-xs-12 custom-width-res-1">
  <div class="hot-coll-box">
    <a href="<%= user_path(user.address) %>">
      <div class="hot-coll-img" style="background-image: url(/assets/<%= url_for(user.banner_image) %>)">
        <%= image_tag url_for(user.banner_image), class: 'img-responsive' %>
      </div>
      <div class="hot-coll-content">
        <h4><%= t('common.collections')%></h4>
        <p data-toggle="tooltip" data-placement="top" title="<%= user.full_name %>"><span>by</span> <%= user.full_name %></p>
      </div>
    </a>
  </div>
</div>

app/views/dashboard/_notification.html.erb
<% if @notifications.present? %>
  <% @notifications.each do |activity| %>
    <%# next if ((activity.item_type == "Bid" && (!activity.item.user.present? || !activity.item.collection.present?)) || activity.item_type == "Like" && (!activity.item.user.present? || !activity.item.collection.present?)) %>
    <% next if (
      (activity.item_type == "Bid" && ((!activity.item.user.present? || !activity.item.collection.present?) ||
        (activity.item.user == current_user && (activity.event == 'update' && 
          !activity.changeset.keys.include?("state")
        )) ||
        (activity.item.owner == current_user && activity.event != 'create')
      )) ||
      (activity.item_type == "Like" && (!activity.item.user.present? || !activity.item.collection.present?)) ||
      (activity.item_type == "Follow" && (!activity.item.follower.present? || !activity.item.followee.present?)) ||
      (activity.item_type == "User" && (activity.event == 'create' || (activity.changeset["is_verified"].present? && !activity.changeset["is_verified"].last))) ||
      (activity.item_type == "Collection" && activity.event == "update" && (
          !Collection.is_valid_activity(activity) || !activity.changeset.keys.include?("owner_id")
        )
      )
    ) %>

    <li>
        <div class="notifier-elements">
          <% if activity.item_type == "Follow" %>
            <div class="notification-list-img">
              <%= image_tag url_for(activity.item.follower.profile_image(:icon)), class: 'img-responsive' %>
            </div>
            <a class="notification-list-content" href="javascript:void(0);">
              <h4 data-toggle="tooltip" data-placement="top" title="<%= activity.item.follower.full_name %>"><%= activity.item.follower.full_name %></h4>
              <p class="para-color" data-toggle="tooltip" data-placement="top" title="started following">started following</p>
            </a>
          <% elsif activity.item_type == "Like" %>
            <div class="notification-list-img">
              <%= image_tag url_for(activity.item.user.profile_image(:icon)), class: 'img-responsive' %>
            </div>
            <a class="notification-list-content" href="javascript:void(0);">
              <h4 data-toggle="tooltip" data-placement="top" title="liked">@<%= activity.item.user.full_name %> liked</h4>
              <p class="para-color" data-toggle="tooltip" data-placement="top" title="<%= activity.item.collection.name %>"><%= activity.item.collection.name %></p>
            </a>
          <% elsif activity.item_type == "Bid" %>
            <div class="notification-list-img">
              <%= image_tag url_for(cover_url(activity.item.collection)), class: 'img-responsive' %>
            </div>
            <%= link_to collection_path(id: activity.item.collection.address, tab: 'bid'), class: "notification-list-content" do %>
              <% if activity.item.owner == current_user && activity.event == 'create' %>
                <h4 data-toggle="tooltip" data-placement="top"><%= activity.item.user.full_name %></h4>
                <p class="para-color" data-toggle="tooltip" data-placement="top">offered <%= activity.item.crypto_currency %> <%= activity.item.crypto_currency_type %></p>
              <% end %>
              <% if activity.item.user == current_user && activity.event == 'update' %>
                <h4 data-toggle="tooltip" data-placement="top"><%= activity.item.user.full_name %></h4>
                <% if activity.changeset["state"] == ['pending', 'executed'] %>
                  <p class="para-color" data-toggle="tooltip" data-placement="top">Your bid have been accepted by <%= activity.item.owner.full_name %></p>
                <% elsif activity.changeset["state"] == ['pending', 'expired'] %>
                  <p class="para-color" data-toggle="tooltip" data-placement="top">Your bid Expired by <%= activity.item.owner.full_name %></p>
                <% end %>
              <% end %>
            <% end %>
          <% elsif activity.item_type == 'Collection' %>
            <div class="notification-list-img">
              <%= image_tag url_for(cover_url(activity.item)), class: 'img-responsive' %>
            </div>
            <%= link_to collection_path(id: activity.item.address), class: "notification-list-content" do %>
              <% if activity.event == 'create' %>
                <h4 data-toggle="tooltip" data-placement="top"><%= activity.item.name %></h4>
                <!--<p class="para-color" data-toggle="tooltip" data-placement="top" >Minted by <%#= activity.item.creator.full_name %></p> -->
                <p>Minted by <%= activity.item.creator.full_name %></p>
              <% end %>
              <% if activity.event == 'update' && activity.changeset["owner_id"].present? %>
                <h4 data-toggle="tooltip" data-placement="top"><%= activity.item.name %></h4>
                <p class="para-color" data-toggle="tooltip" data-placement="top">Transferred from <%= activity.reify.owner.full_name %></p>
              <% end %>
            <% end %>
          <% elsif activity.item_type == "User" %>
            <div class="notification-list-img">
              <%= image_tag url_for(current_user.profile_image(:icon)), class: 'img-responsive' %>
            </div>
            <a class="notification-list-content" href="javascript:void(0);">
              <h4 data-toggle="tooltip" data-placement="top" title="liked">Profile successfully verified</h4>
            </a>
          <% end %>

          <div class="notification-list-timings" data-toggle="tooltip" data-placement="top" title="<%= time_ago_in_words(activity.created_at).capitalize %>">
            <%= time_ago_in_words(activity.created_at).capitalize %>
          </div>
        </div>
    </li>
  <% end %>
<% else %>
  <div class="notify_empty">
    <img src="/assets/notification-bell.svg" />
    <h4><%= t('common.no_new_notifications')%></h4>
  </div>
<% end %>

app/views/dashboard/_notification_new.html.erb
<% if @notifications.present? %>
  <% @notifications.each do |notification| %>
    <li>
      <div class="notifier-elements">
        <%= link_to "#{notification.redirect_path}", class: 'notify_link' do %>
          <div class="notification-list-img">
            <%= image_tag notification.image_url, class: 'img-responsive' %>
          </div>
          <div class="notification-list-content">
            <p class="para-color" data-toggle="tooltip" data-placement="top" title="notification message"><%= notification.message %></p>
            <div class="notification-list-timings" data-toggle="tooltip" data-placement="top" title="time ago">
              <%= time_ago_in_words(notification.created_at).capitalize %>
            </div>
          </div>
        <% end %>
        
      </div>
    </li>
  <% end %>
<% else %>
  <div class="notify_empty">
    <img src="/assets/notification-bell.svg" />
    <h4><%= t('common.no_new_notifications')%></h4>
  </div>
<% end %>

app/views/dashboard/_top_buyers.html.erb
<section class="row row--grid">
  <!-- title -->
  <div class="col-12">
    <div class="main__title">
      <h2><%= t('dashboard.top_buyers')%></h2>

      <!--<a href="#" class="main__link">View all <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17.92,11.62a1,1,0,0,0-.21-.33l-5-5a1,1,0,0,0-1.42,1.42L14.59,11H7a1,1,0,0,0,0,2h7.59l-3.3,3.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l5-5a1,1,0,0,0,.21-.33A1,1,0,0,0,17.92,11.62Z"/></svg></a>-->
    </div>
  </div>
  <!-- end title -->

  <!-- sellers list -->
  <div class="col-12">
    <ul class="sellers-list">
      <% if @top_buyers.present? %>
        <% @top_buyers.each_with_index do |seller, i| %>
          <li class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="sellers-list__author sellers-list__author--verified">
              <%= image_tag seller.profile_image %>
              <% if seller.is_verified %>
                <i class="fa fa-check-circle" aria-hidden="true"></i>
              <% end %>
              <span class="sellers-list__number"><%=i+1%></span>
              <%= link_to seller.full_name,user_path(id: seller.address)  %>
              <span data-toggle="tooltip" data-placement="top" title="<%#= seller.total_sell %>"><%#= seller.total_sell %></span>
            </div>
          </li>
        <% end %>
      <% else %>
        <% 4.times do %>
          <%= render partial: 'common/empty_topbuyers' %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <!-- end sellers list -->
</section>

app/views/dashboard/_top_sellers.html.erb
<section class="row row--grid">
  <!-- title -->
  <div class="col-12">
    <div class="main__title">
      <h2><%= t('dashboard.top_sellers')%></h2>

      <!--<a href="#" class="main__link">View all <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17.92,11.62a1,1,0,0,0-.21-.33l-5-5a1,1,0,0,0-1.42,1.42L14.59,11H7a1,1,0,0,0,0,2h7.59l-3.3,3.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l5-5a1,1,0,0,0,.21-.33A1,1,0,0,0,17.92,11.62Z"/></svg></a>-->
    </div>
  </div>
  <!-- end title -->

  <!-- sellers list -->
  <div class="col-12">
    <ul class="sellers-list">
      <% if @top_sellers.present? %>
        <% @top_sellers.each_with_index do |seller, i| %>
          <li class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="sellers-list__author sellers-list__author--verified">
              <%= image_tag seller.profile_image %>
              <% if seller.is_verified %>
                <i class="fa fa-check-circle" aria-hidden="true"></i>
              <% end %>
              <span class="sellers-list__number"><%=i+1%></span>
              <%= link_to seller.full_name,user_path(id: seller.address)  %>
              <span data-toggle="tooltip" data-placement="top" title="<%#= seller.total_sell %>"><%#= seller.total_sell %></span>
            </div>
          </li>
        <% end %>
      <% else %>
        <% 4.times do %>
          <%= render partial: 'common/empty_topbuyers' %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <!-- end sellers list -->
</section>

app/views/dashboard/_user_card.html.erb
<div class="col-md-3 col-sm-6 col-xs-12 custom-width-res-1">
  <div class="featured-creators-box">
    <div class="featured-creators-box-img">
      <div class="featured-creators-box-img-bg" style="background-image:url(<%= url_for user.banner_image %>)">
        <img src="assets/bg-1.jpg" class="img-responsive">
      </div>
      <div class="featured-creators-box-img-profile">
        <%= image_tag url_for(user.profile_image), class: "img-responsive" %>
      </div>
    </div>
    <div class="featured-creators-box-content">
      <h4><%= user.full_name %></h4>
      <a href="https://twitter.com/<%= user.twitter_link %>" target="_blank">@<%= user.twitter_link %></a>
    </div>
  </div>
</div>

app/views/dashboard/notifications.js.erb
$(".user-notification-list li").remove();
$('.user-notification-list').html('<%= j(render "notification_new") %>');
$(".notification_count").text("0")

app/views/dashboard/search.html.erb
<%if false%>
<section class="token-constructions">
  <div class="container">
    <div class="row margin-top-minus-20">

        <div class="col-md-12">
          <div class="col-xs-12 dis-padd-lr-0-res">

            <div class="row pb-15 pt-30">
              <div class="input-element-form-search" style="background-image: linear-gradient(to right, #00000047 , #000000cf), url(/assets/searchbg.jpg)">

                  <div class="search-block">
                    <h3><%= t('dashboard.search_collections')%></h3>
                    <%=form_tag search_path, :method=>:get do%>
                      <i class="fa fa-search"></i>
                      <input type="text" name="query" class="searchInputPage" id="searchInput" placeholder="Search by creator, collectible or collection" value="<%=params[:query]%>">
                      <div id='submitsearch' style="">
                        <span><%= t('dashboard.search')%></span>
                      </div>
                    <%end%>
                  </div>
              </div>
              
            </div>

            <div class="row pb-15 pt-30">
              <div class="col-md-12 col-sm-12 col-xs-12 dis-heading-width">
                <h3 class="mt-0"><%= t('dashboard.search_results', query: params[:query])%></h3>
              </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="ul-width-passing">
                <ul class="nav nav-tabs token-list-details">
                  <li class="<%=params[:tab]!='users' ? 'active': ''%>">
                    <%=link_to t('dashboard.items'), search_path(query: params[:query])%>
                  </li>
                  <li class="<%=params[:tab]=='users' ? 'active': ''%>">
                    <%=link_to t('dashboard.users'), search_path(tab: "users", query: params[:query])%>
                  </li>

                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-12 pt-10 tabs-content-bg border-custom-style">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="tab-content pt-20">


                    <div id="items" class="tab-pane fade in <%=params[:tab]!='users' ? 'active': ''%>">
                        <div class="row" style="">
                        <% @collections and @collections.each do |collection| %>
                            <%= render "collection_card", collection: collection %>
                        <% end %>
                        </div>
                     </div>
                    <div id="users" class="tab-pane fade in <%=params[:tab]=='users' ? 'active': ''%>">
                      <div class="row">
                        <% @users and @users.each do |user| %>
                            <%= render "user_card", user: user %>
                        <% end %>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</section>
<%end%>
<main class="main">
<div class="container">
      <div class="row row--grid">
        <!-- title -->
        <div class="col-12">
          <div class="main__title main__title--page">
            <h1><%= t('dashboard.explore_digital_assets')%></h1>
          </div>
        </div>
        <!-- end title -->

        <!-- filter -->
        <div class="col-12">
          <div class="main__filter">
             <%=form_tag search_path, :method=>:get, :class=>'main__filter-search' do%>
              <input type="text" name="query" placeholder="Search..." value="<%=params[:query]%>">
              <button type="submit"><i class="fas fa-search"></i></button>
            <%end%>

            <div class="main__filter-wrap">
              <!--<select class="main__select" name="status">
                <option value="now">Buy Now</option>
                <option value="new">New</option>
                <option value="auction">On Auction</option>
                <option value="offers">Has Offers</option>
              </select>-->

              
              <% if @collections.present? %>
                <div class="category_menu header__action header__action--profile">
                  <a class="" href="javascript:void(0);" role="button" id="dropdownMenuFilter" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= params[:category] || 'All Categories' %>                   
                    <i class="fas fa-chevron-down"></i>

                  </a>

                  <ul class="dropdown-menu header__profile-menu" aria-labelledby="dropdownMenuProfile">
                    <li><%= link_to 'All Categories', category_filter_path(query: params[:query]) , remote: true%></li>
                  <% Category.all.each do |category| %>
                    <li>
                      <%= link_to category.name, category_filter_path(category: category.name,query: params[:query]) , remote: true%>
                    </li>
                    <%end%>
                  </ul>
                </div>
              <%end%>
            </div>
          </div>
        </div>
        <!-- end filter -->
      </div>
      <div class="filters-content">
        <div class="row row--grid">
          <% if @collections.present? %>
            <% @collections.each do |collection| %>
              <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
                <%=render "dashboard/collection_card", collection: collection%>
              </div>
            <% end %>
          <% else %>
          <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
              <h3><%= t('dashboard.no_data_found')%></h3>
              </div>
          <% end %>
        </div>
      </div>
      <!-- paginator -->
      
      <!-- end paginator -->
    </div>
</main>

app/views/dashboard/top_buyers_and_sellers.js.erb
<% if params[:user_type] == 'sellers' %>
  $(".top-sellers-value").html("<%= escape_javascript(render partial: "top_sellers") %>");
<% elsif params[:user_type] == 'buyers' %>
  $(".top-buyers-value").html("<%= escape_javascript(render partial: "top_buyers") %>");
<% end %>