config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    devise_for :admin_users, controllers: {
      sessions: 'admin/admin_users/sessions',
    }
    resources :users do
      collection do
        get :reports
      end

      member do
        get :collections
        get :approve
        get :deny
        get :enable
        get :verify
      end
    end
    resources :categories
    resources :fees
    resources :featured_users, except: [:edit, :update]
    resources :featured_collections, except: [:edit, :update]
    resources :transactions, only: [:index]

    get 'dashboard', to: 'dashboard#index'
    root to: 'dashboard#index'
  end

  resources :users, except: [:index, :create, :destroy] do
    collection do
      get :following
      get :follow
      get :unfollow
      get :load_tabs
      post :like
      post :unlike
      post :bid
      post :report
      post :create_contract
    end
  end
  resources :collections, only: [:new, :show, :create]  do
    member do
      get :remove_from_sale
      get :fetch_details
      get :fetch_transfer_user
      post :bid
      post :buy
      post :sell
      post :update_token_id
      post :change_price
      post :transfer_token
      post :sign_metadata_hash
      post :sign_fixed_price
      post :owner_transfer
      post :burn
    end
  end

  resources :sessions, only: [:create, :destroy] do
    collection do
      get :valid_user
    end
  end
  resources :likes, only: [:create, :update]
  resources :bids
  resources :fees

  ### CUSTOM ROUTES
  get 'dashboard', to: 'dashboard#index'
  get 'top_buy_sell', to: 'dashboard#top_buyers_and_sellers'
  get 'my_items', to: 'users#my_items'
  get 'activities', to: 'activities#index'
  get 'load_more_activities', to: 'activities#load_more'
  get 'search', to: 'dashboard#search'
  get 'notifications', to: 'dashboard#notifications'
  get 'contract_abi', to: 'dashboard#contract_abi'
  get 'category_filter', to: 'dashboard#set_categories_by_filter'

  ### STATIC PAGES
  get 'about', to: 'static#about'
  get 'faq', to: 'static#faq'
  get 'terms_conditions', to: 'static#terms_conditions'
  get 'privacy', to: 'static#privacypolicy'

  ### ROOT PAGE
  root to: "dashboard#index"

  ### THIRD-PARTY ROUTES
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/common/_collection_card.html.erb
<% if current_user %>
  <%= react_component("collections/like", address: current_user.address, likes: @likes, collectionId: collection.id) %>
<% else %>
  <div class="explore-bids-icon-heart no-wishlist">
    <i class="fa fa-heart"></i>
  </div>
<% end %>

<%= link_to collection_path(collection.address) do %>
  <div class="explore-bids-img" style="background-image: url('<%= cover_url(collection) %>');">
    <%= image_tag cover_url(collection), class: "img-responsive" %>
  </div>
<% end %>

<div class="explore-bid-opt-img">
  <%= render partial: 'common/collection_owner_imgs', locals: {collection: collection} %>

  <div class="explore-bid-opt-icon">
    <div class="dropdown">
      <div class="more-list dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-ellipsis-v"></i>
      </div>
      <ul class="dropdown-menu">
        <% if collection.instant_sale_enabled %><li><%= link_to t('shared.buy_now'), collection_path(collection.address), anchor: '#Buy-modal' %></li><% end %>
        <% if collection.put_on_sale %><li><a href="<%= collection_path(collection.address) %>"><%= t('collections.show.place_a_bid')%></a></li><% end %>
        <li><a href="#"><%= t('collections.show.report')%></a></li>
      </ul>
    </div>
  </div>
</div>
<div class="explore-bids-content">
  <div>
    <h4><%= collection.title %></h4>
    <p><%= collection.title_desc %></p>
  </div>
  <% if collection.max_bid %>
    <p class="bid_status">Highest bid <b><%= collection.max_bid.value %></b></p>
  <% end %>
</div>

app/views/common/_collection_owner_imgs.html.erb
<div class="explore-bid-auth-img">
  <%= image_tag collection_type_img(collection), class: 'img-responsive' %>
  <%= render partial: 'common/user_img', locals: {user: collection.creator} %>
  <%= render partial: 'common/user_img', locals: {user: collection.owner} %>
</div>

app/views/common/_empty.html.erb
<div class="no-details" style="">
  <h3 class="color-grey"><%= t('shared.no_data_found')%></h3>
</div>

app/views/common/_empty_activity.html.erb
<div class="activity dummy-activity">
        <a class="activity__cover" href="javascript:void(0);">
            <img src="/assets/banner-bg.jpeg" width="140" height="162">
</a>      <div class="activity__content">
        <h3 class="activity__title">
            <a href="javascript:void(0);">
                <%= t('collections.collection_name')%>
</a>
        </h3>
        <p class="activity__text"><%= t('collections.liked_by')%>
          <a href="javascript:void(0);">
              @User name
          </a>  <br>
          <span class="activity__time">about 2 hours </span>
      </p></div>
    </div>

app/views/common/_empty_card_collection.html.erb
<div class="card dummy-explorer">
    <div class="t_c">
        <a href="javascript:void(0);" class="card__cover">
            <span class="collection-card-img" style="background-image: url('/assets/banner-bg.jpeg')">
                <img src="/assets/banner-bg.jpeg" />
            </span>
        </a>
        <button class="card__likes heart is-active"><i class="far fa-heart"></i><i class="fas fa-heart"></i><span>1</span></button>
    </div>
    <h3 class="card__title" data-toggle="tooltip" data-placement="top" title="" data-original-title="Image New 003 / 1 of 1">
        <a href="javascript:void(0);"><%= t('collections.collection_name')%></a>
    </h3>
    <div class="card__author">
        <img src="/assets/default_user.png">
        <a href="javascript:void(0);">@0x00aeccc...daf0</a>
    </div>
    <div class="card__info">
        <div class="card__price">
            <span><%= t('shared.reserve_price')%></span>
            <span>0.00001 ETH</span> 
        </div>
    </div>
</div>

app/views/common/_empty_topbuyers.html.erb
<li class="col-12 col-sm-6 col-md-4 col-lg-3 dummy-topbuyer">
    <div class="sellers-list__author sellers-list__author--verified">
    <img src="/assets/default_user.png">
    <span class="sellers-list__number">1</span>
    <a href="javascript:void(0)">0xad00de4...485d</a>
    <span data-toggle="tooltip" data-placement="top" title="" data-original-title=""></span>
    </div>
</li>

app/views/common/_footer.html.erb
<%if false%>
    <footer class="pt-50 pb-15">
      <div class="container-fluid padding-lr-custom-50">
        <div class="row ml-0 mr-0">
          <div class="col-md-12">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="footer-logo">
                <h4><%= image_tag Rails.application.credentials.config[:app_logo], class: 'img-responsive logo-img' %></h4>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="quick-link">
                <h4>><%= t('footer.quick_links') %></h4>
                <ul>
                  <li>
                    <a><%= t('footer.about') %></a>
                  </li>
                  <li>
                    <a href="<%= root_path %>"><%= t('footer.explore') %></a>
                  </li>
                  <li>
                    <a><%= t('footer.HIW') %></a>
                  </li>
                  <li>
                    <a><%= t('footer.support') %></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="community">
                <h4><%= t('footer.community') %></h4>
                <ul>
                  <li>
                    <a><%= t('footer.discussion') %></a>
                  </li>
                  <li>
                    <a><%= t('footer.voting') %></a>
                  </li>
                  <li>
                    <a><%= t('footer.suggest_feature') %></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="social-media">
                <h4><%= t('footer.social_media') %></h4>
                <ul>
                  <li>
                    <a href="javascript:void(0);">
                      <i class="fa fa-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0);">
                      <i class="fa fa-instagram"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0);">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:void(0);">
                      <i class="fa fa-youtube"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row ml-0 mr-0">
          <div class="col-md-12">
            <hr>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <p class="copyrights">© <%= Rails.application.credentials.config[:app_name] %>, Inc. All rights reserved.</p>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="li-copy">
                <ul>
                  <li><a><%= t('footer.tc') %></a></li>
                  <li><a><%= t('footer.privacy_policy') %></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
<%end%>


<!-- end get started -->

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4 order-1 order-md-1 order-lg-1 order-xl-1">
        <%= image_tag Rails.application.credentials.config[:app_logo], class: 'img-responsive logo-img' %>
        <p class="footer__tagline">
          <%= t('footer.tag_line', app_name: Rails.application.credentials.config[:app_name]) %>
        </p>
      </div>

      <div class="col-12 col-md-12 col-lg-12 col-xl-2 order-2"></div>

      <div class="col-6 col-md-3 col-lg-3 col-xl-2 order-2 order-md-2 order-lg-2 order-xl-2 offset-md-0 offset-lg-0">
        <h6 class="footer__title"><%= Rails.application.credentials.config[:app_name] %> Marketplace</h6>
        <div class="footer__nav">
          <a href="/about">About <%= Rails.application.credentials.config[:app_name] %> </a>
          <a href="/privacy">Privacy</a>
          <a href="/terms_conditions">Terms & Conditions</a>
          <a href="/faq">Faq / How to</a>
        </div>
      </div>

      <!-- <div class="col-12 col-md-6 col-lg-6 col-xl-4 order-4 order-lg-4 order-md-4 order-xl-3">
        <div class="row">
          <div class="col-12">
            <h6 class="footer__title"><%#= t('footer.explore') %></h6>
          </div>

          <div class="col-6">
            <div class="footer__nav">
              <a href="javascript:void(0);"><%#= t('footer.art') %></a>
              <a href="javascript:void(0);"><%#= t('footer.photography') %></a>
              <a href="javascript:void(0);"><%#= t('footer.games') %></a>
              <a href="javascript:void(0);"><%#= t('footer.music') %></a>
            </div>
          </div>

          <div class="col-6">
            <div class="footer__nav">
              <a href="javascript:void(0);"><%#= t('footer.domains') %></a>
              <a href="javascript:void(0);">DeFi</a>
              <a href="javascript:void(0);">Metaverses</a>
              <a href="javascript:void(0);">Memes</a>
            </div>
          </div>
        </div>
      </div> -->

      <div class="col-12 col-md-1 col-lg-1 col-xl-2 order-3 my-commere"></div>

      <div class="col-6 col-md-3 col-lg-3 col-xl-2 order-3 order-lg-3 order-md-3 order-xl-4">
        <h6 class="footer__title">Community</h6>
        <div class="footer__nav">
          <a href="https://pownedco.zendesk.com/hc/en-us" target="_blank">Help Center</a>
          <a href="<%= Rails.application.credentials.config[:discussion_url] %>" target="_blank">Discussion</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="footer__content">
          <div class="footer__social">
            <a href="https://discord.com/channels/877419350024417331/877419350024417333" target="_blank" class="socialite-icon">
              <%= image_tag "/assets/discord.png", class: 'img-responsive' %>
            </a>
            <a href="https://www.instagram.com/pownedco/" target="_blank" class="socialite-icon">
              <%= image_tag "/assets/instagram.png", class: 'img-responsive' %>
            </a>
            <a href="https://twitter.com/pownedco" target="_blank" class="socialite-icon">
              <%= image_tag "/assets/twitter.png", class: 'img-responsive' %>
            </a>
            <a href="https://www.tiktok.com/@pownedco" target="_blank" class="socialite-icon">
              <%= image_tag "/assets/tik-tok.png", class: 'img-responsive' %>
            </a>

            <!-- <a href="javascript:void(0);" target="_blank"><i class="fab fa-facebook-f"></i></a>
            <a href="javascript:void(0);" target="_blank"><i class="fab fa-telegram-plane"></i></a> -->
          </div>

          <small class="footer__copyright">© <%= Rails.application.credentials.config[:app_name] %>, 2021.</small>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/common/_header_top.html.erb
<div class="header__top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="top_menu">
            <ul>
              <li><a href="<%= Rails.application.credentials.config[:support_url] %>" target="_blank">><%= t('header.help_center') %></a></li>
              <li><a href="<%= Rails.application.credentials.config[:discussion_url] %>" target="_blank">><%= t('footer.discussion') %></a></li>
            </ul>
          </div>
        </div>
        <!--<div class="col-lg-6 col-md-6 col-sm-6">-->
          <!--<div class="head__lang">-->
            <!--<a class="head__lang-btn" href="javascript:void(0);" role="button" id="dropdownLang" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
              <!--<img src="img/flags/uk.svg" alt="">-->
              <!--<span>English</span>-->
            <!--</a>-->
            <!--<ul class="dropdown-menu head__lang-dropdown" aria-labelledby="dropdownLang">-->
              <!--<li><a href="javascript:void(0);"><img src="img/flags/spain.svg" alt=""><span>Spanish</span></a></li>-->
              <!--<li><a href="javascript:void(0);"><img src="img/flags/russia.svg" alt=""><span>Russian</span></a></li>-->
              <!--<li><a href="javascript:void(0);"><img src="img/flags/china.svg" alt=""><span>Chinese</span></a></li>-->
            <!--</ul>-->
          <!--</div>-->
        <!--</div>-->
      </div>
    </div>
  </div>

app/views/common/_my_header.html.erb
<header class="header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="header__content">
          <%= render "common/nav_header" %>
          
          <%= render "common/search" %>
          <%= render "common/static_nav" %>

          <div class="header__actions">
            <div class="header__action header__action--search">
              <button class="header__action-btn" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
            </div>

            <div class="dropdown desktop-notification">
              <a data-toggle="dropdown" class="view-notification" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bell"></i>
                <p class="notification_count"><%= Notification.unread(current_user).count %></p>
              </a>
              <div class="dropdown-menu header__profile-menu ">
              <h4 class="heading">
                <!-- <i class="fa fa-bell"></i>&nbsp; -->
                <%= t('header.notifications') %>
              </h4>
                <ul class="user-notification-list"></ul>
              </div>
            </div>

            <div class="header__action header__action--profile">
              <a class="header__profile-btn header__profile-btn--verified" href="javascript:void(0);" role="button" id="dropdownMenuProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag url_for(current_user.profile_image), class: "img-responsive" %>
                    <% if current_user.is_verified %>
                        <i class="fa fa-check-circle" aria-hidden="true"></i>
                    <% end %>
                    <div><p><%= current_user.full_name %></p>
                      <span><%= current_balance %> <%= Rails.application.credentials.config[:app_coin] %></span></div>
                    <i class="fas fa-chevron-down"></i>
              </a>

              <ul class="dropdown-menu header__profile-menu" aria-labelledby="dropdownMenuProfile">
                <li><a href="<%=my_items_path%>"><i class="far fa-user"></i><span><%= t('header.profile') %></span></a></li>
                <li><a href="<%=edit_user_path(current_user)%>"><i class="fas fa-cog"></i><span><%= t('header.settings') %></span></a></li>
                <li><a href="<%= activities_path(activity_type: "activity") %>"><i class="fas fa-list"></i> <span><%= t('header.activity') %></span></a></li>
                <li><a href="<%= Rails.application.credentials.config[:support_url] %>"><i class="far fa-medkit" target="_blank"></i><span><%= t('header.help_center') %></span></a></li>
                <li><a href="<%= Rails.application.credentials.config[:discussion_url] %>"><i class="far fa-comments" target="_blank"></i><span><%= t('header.discussion') %></span></a></li>

                <li><a href="javascript:void(0);" onclick="window.disconnect(<%= current_user.address %>)"><i class="fas fa-sign-out-alt"></i> <span><%= t('header.sign_out') %></span></a></li>
              </ul>
            </div>

            <%= render partial: 'common/language_select' %>

            <button class="header__btn" type="button">
              <span></span>
              <span></span>
              <span></span>
            </button>
          </div>


        </div>
      </div>
    </div>
  </div>
</header>

<script type="text/javascript">
    var address = "<%= current_user.address %>"

    $(document).ready(function () {
        window.loadUser(address)
    })
</script>

app/views/common/_search.html.erb
       <%= form_tag search_path, :method => :get ,:class=> "header__search" do %>
        <input type="text" name="query"   value="<%=params[:query]%>" placeholder="Search items, collections, and creators">
        <button type="search"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
        <button type="button" class="close"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M13.41,12l6.3-6.29a1,1,0,1,0-1.42-1.42L12,10.59,5.71,4.29A1,1,0,0,0,4.29,5.71L10.59,12l-6.3,6.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0L12,13.41l6.29,6.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42Z"></path></svg></button>

        
      <%end%>

app/views/common/_static_nav.html.erb
<%if false%>
<ul class="nav navbar-nav">
  <li class="active"><a href="<%= root_path %>">Explore</a></li>
  <li><a href="javascript:void(0);">How its works</a></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0);">Community <span class="caret"></span></a>
    <ul class="dropdown-menu community-ddm">
      <!-- <li><a href="javascript:void(0);">NFT Token</a></li> -->
      <li><a href="<%= Rails.application.credentials.config[:discussion_url] %>" target="_blank">Discussion</a></li>
<!--      <li><a href="javascript:void(0);">Voting</a></li>-->
      <li><a href="javascript:void(0);">Suggest feature</a></li>
      <li><a href="javascript:void(0);">Subscribe</a></li>
      <li class="divider"></li>
      <li class="communit-ddm-social-media">
        <a href="javascript:void(0);">
          <i class="fa fa-telegram"></i>
        </a>
        <a href="javascript:void(0);">
          <i class="fa fa-instagram"></i>
        </a>
        <a href="javascript:void(0);">
          <i class="fa fa-youtube"></i>
        </a>
      </li>
    </ul>
  </li>
  <button type="button" class="navbar-toggle navbar-break-btn" data-toggle="collapse" data-target="#myNavbarCustom">
    <button class="hamburger">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    <button class="cross">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>                    
  </button>
</ul>
<%end%>
 <div class="header__menu">
        <ul class="header__nav">
           
          <li class="header__nav-item">
            <a class="header__nav-link" href="<%= search_path%>">Explore</a>
          </li>
          <li class="header__nav-item">
             <%if current_user.is_approved%>
                  <a href="<%=new_collection_path%>" class="header__nav-link">Create</a>
             <%end%>
          </li>
          <li class="header__nav-item">
            <a href="<%= activities_path(activity_type: "activity") %>" class="header__nav-link">Activity</a>
          </li>
          <!--<li class="header__nav-item">
            <a href="#" class="header__nav-link">Community</a>
          </li>-->
        </ul>
      </div>

app/views/common/_terms.html.erb
<div id="terms-and-condition" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4 class="modal-title"><%= t('footer.tc') %></h4>

  <div class="modal-body pl-30 pr-30">
    <%= hidden_field_tag "account", nil %>
    <%= hidden_field_tag "eth_balance_tc", nil %>
    <%= hidden_field_tag "network_type", nil %>

    <input class="styled-checkbox" id="condition1" type="checkbox" name="condition1" value="Bike">
    <label for="condition1"><%= t('header.age_limit') %></label>

    <input class="styled-checkbox" id="condition2" type="checkbox" name="condition2" value="Bike">
    <label for="condition2"><%= t('header.tc_acceptence') %></label>

    <a href="javascript:void(0);" onclick="window.proceedWithLoad()" class="theme-btn proceedBtn"><%= t('header.proceed') %></a>
  </div>
</div>

app/views/common/_user_balance.html.erb
<a class="dropdown-toggle profile-section" data-toggle="dropdown" href="javascript:void(0);">
  <div class="profile-list">
    <div class="profile-list-img">
      <%= image_tag url_for(current_user.profile_image(:thumb)), class: "img-responsive" %>
      <% if current_user.is_verified %>
        <i class="fa fa-check-circle" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class="profile-list-content">
      <h5><span class="curBalance"><%= current_balance %></span> <%= Rails.application.credentials.config[:base_coin] %></h5>
      <p class="para-color"><%= current_user.masked_address %></p>
    </div>
    <div class="profile-list-icon">
      <i class="fa fa-angle-down"></i>
    </div>
  </div>
</a>

app/views/common/_wallet_connect.html.erb
<div id="connect_to_wallet" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button>
  <h4><%= t('header.connect_wallet') %></h4>
  <p><%= t('header.wallet_help') %> <a href="#what-wallet" class="open-modal"><%= t('header.wallet_info') %></a></p>

  <div class="w_btn">
    <a href="javascript:void(0);" onclick="window.connect()">
      <span class="w_btn_icon"><img src="/assets/metamask.png"></span>
      <%= t('header.metamask_wallet') %>
    </a>
  </div>
  <p class="mt-20"><%= t('header.wallet_confi') %></p>
</div>


<div id="what-wallet" class="zoom-anim-dialog mfp-hide modal sm_modal">
  <!-- <button class="modal__close md_cls" type="button"><i class="fas fa-times"></i></button> -->
  <a class="open-modal default-modal-element" href="#connect_to_wallet">
    <i class="fas fa-times"></i>
  </a>
  <h4 class="modal-title">What is a wallet?</h4>
  <p>Wallets are used to send, receive, and store digital assets like Ether. Wallets come in many forms. They are either built into your browser, an extension added to your browser, a piece of hardware plugged into your computer, or even an app on your phone.</p>
</div>


<script type="text/javascript">
  $('#text-what-is-wallet').click(function(){
    $("#connect_to_wallet .modal__close").click();
  });
  // $('#what-wallet .modal__close').click(function(){
  //   $('#connect-wallet-modal').magnificPopup({
  //       type: 'inline',
  //       preloader: false,
  //       modal: true
  //   });
  // });
</script>